name: Generate snake animation

on:
  schedule:
    # Chạy lúc phút 0, mỗi 12 giờ: 00:00 và 12:00 UTC
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write    # Cho phép ghi nội dung repo (commit/push)
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Giới hạn 5 phút cho job

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg?palette=github-dark

      # 3) Đẩy dist/snake.svg lên branch `output`
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
